### ISSUE TITLE
boom error

### ISSUE THREAD

**Issue by xiaocheng168** [WeidosOddities/Extended-Bogeys-Borked#12]
**Bug Report**

**Description:**
The game crashes when launching due to a missing mod dependency for `Extended Bogeys`. Specifically, the mod requires the `railways` mod, which is not currently installed.

**To Reproduce:**
1. Use `Extended Bogeys` mod, version `0.5.13.0-1.20.1-0.5.1.f-forge`.
2. Minecraft version: `1.20.1`.
3. Ensure that the `railways` mod is not installed in the modlist.
4. Launch Minecraft with Forge.

**Expected Behavior:**
The game should load properly without crashing, provided that all required dependencies, including `railways`, are installed.

**Screenshots:**
If available, include a screenshot or crash log image (example image provided).

**Additional Context:**
The crash report mentions that the `Extended Bogeys` mod requires `railways` to be installed but it is currently missing. This causes a failure during mod loading.

**Error Details:**

```
Failure message: Mod extendedbogeys requires railways any
Currently, railways is not installed
```

**System Details:**
- Minecraft Version: `1.20.1`
- Operating System: `Windows 10`
- Java Version: `17.0.1`
- Forge Version: `47.1.43`
- Mod Version: `Extended Bogeys 0.5.13.0-1.20.1-0.5.1.f-forge`

**Suggested Fix:**
Install the `railways` mod, which is a dependency of `Extended Bogeys`. This should resolve the issue by satisfying the missing mod requirement.

![image](https://github.com/user-attachments/assets/9df4947b-a6c4-461e-82f5-e10efdeab951)

**Comment by WeidosOddities** [comment]
EB requires Create: Steam N'Rails as a dependency
