### ISSUE TITLE
Changing sizes not working anymore :(

### ISSUE THREAD

**Issue by average-dummkopf** [WeidosOddities/Extended-Bogeys-Borked#2]
Changing bogey sizes ain't working anymore. Whenever I try to change sizes, it just creates a new bogey, not change the old ones size.

1. Extended Bogeys  0.5.7, and 0.5.5 (haven't checked 0.5.6), Minecraft version 1.20.1, Create version 0.5.1f
2. Create a new train
3. Choose a bogey style with other sizes
4. Place the bogey
5. Try to change bogey size

Expected behavior:
Bogey size changing

If I was not clear, apologies. [This](https://youtu.be/6jIwPkOeOrE) video should explain it quite nicely.

Not sure if it's happening to other people, could be just me

Edit: It was human error, sorry

**Comment by dtawales** [comment]
Was this fixed? I am having the same problem on 0.5.7
