### ISSUE TITLE
Bogie Rendering Crash Assembling A Train With XL 0-8-0 Bogey

### ISSUE THREAD

**Issue by Tylermaster2** [WeidosOddities/Extended-Bogeys-Borked#4]
**Describe the bug**
Tried to assenble a train with 0-8-0 bogey and gets a crash because of it with the massage like this:
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "com.simibubi.create.content.trains.bogey.BogeyStyle$SizeRenderData.createRenderInstance()" because the return value of "java.util.Map.get(Object)" is null

**To Reproduce**
1. Extended Bogeys v 0.5.9
2. 1.20.1, using Forge 47.2.0
3. build a train with 0-8-0 large bogey
4. Crash happens when assembling train
Crash file:
[crash-2024-05-01_18.49.20-client.txt](https://github.com/WeidosOddities/Extended-Bogeys-Borked/files/15182383/crash-2024-05-01_18.49.20-client.txt)

 It seems to only happen with using XL 0-8-0 Bogey

**Comment by Tylermaster2** [comment]
Sorry Weirdo i forgot my modlist so here it is

**Comment by Tylermaster2** [comment]
Sorry Weirdo i forgot my modlist so here it is
[My Modlist.zip](https://github.com/WeidosOddities/Extended-Bogeys-Borked/files/15195052/My.Modlist.zip)

**Comment by WeidosOddities** [comment]
Sorry I didn't get this sooner, have you tried version 0.5.10/0.5.11 of EB (requires the latest Steam N' Rails)? And or did you update from an older version of EB?

edit: could you also send a crash log/latest.log?

**Comment by Tylermaster2** [comment]
I haven't use 5.10 because it means having to use Steam N' Rails 1.6.1 though now its updated to 1.6.4, and i believe i did update to a newer version of EB on my World.

**Comment by Tylermaster2** [comment]
[latest.log](https://github.com/WeidosOddities/Extended-Bogeys-Borked/files/15284925/latest.log)
Heres the log, but i believe Steam and Rails may also have to do with it too
