### ISSUE TITLE
Extended Bogeys lastest version Problem

### ISSUE THREAD

**Issue by Mrtrainman** [WeidosOddities/Extended-Bogeys-Borked#5]
**Describe the bug**
Extended Bogeys problem

**To Reproduce**
1. EB 5.10
2. version 1.20.1
3. create 5.1f
4. opening minecraft and an error
5. Modlist 
[Modlist.zip](https://github.com/WeidosOddities/Extended-Bogeys-Borked/files/15391969/Modlist.zip)

**Expected behavior**
i used the lastest steam n rails also EB when i open it it has an error has failed to load correctly
**Screenshots**
![Screenshot 2024-05-21 231008](https://github.com/WeidosOddities/Extended-Bogeys-Borked/assets/153827522/eb4f327d-ecab-43b5-84c0-dafc6f4568a0)
**Additional context**
none

**Comment by ff6f8d68** [comment]
because the factory must grow (I don't know why but the factory must grow doesn't work with extended bogeys)

**Comment by ff6f8d68** [comment]
just install this mod: https://modrinth.com/mod/createaddoncompatibility
helped me in this issue
