### ISSUE TITLE
Server crashes but not in single player

### ISSUE THREAD

**Issue by NoxyNixie** [WeidosOddities/Extended-Bogeys-Borked#6]
**Describe the bug**
The server crashes but in single player everything is fine

**To Reproduce**
1. Extended Bogeys Version: 0.5.10
2. Minecraft Version: 1.20.1
3. Create Version: 0.5.1.f
4. Other modlist:  See crash report below

**Expected behavior**
Not to crash on dedicated server.

**Screenshots**
N/A

**Additional context**

[crash-2024-05-30_16.16.09-fml.txt](https://github.com/WeidosOddities/Extended-Bogeys-Borked/files/15505476/crash-2024-05-30_16.16.09-fml.txt)

**Comment by WeidosOddities** [comment]
Update EB to 0.5.11 in the Rabbitminers discord server, there should be a github channel pinned in #extended-bogeys

**Comment by WeidosOddities** [comment]
Should be fixed as of version 0.5.14
