### ISSUE TITLE
failed to load correctly

### ISSUE THREAD

**Issue by ripoy** [WeidosOddities/Extended-Bogeys-Borked#7]
[crash-2024-06-03_07.02.35-fml.txt](https://github.com/user-attachments/files/15527354/crash-2024-06-03_07.02.35-fml.txt)

**Comment by ripoy** [comment]
I might try removing a couple of mods that I think are causing it to not work

**Comment by WeidosOddities** [comment]
There is a mod loading error I should have fixed in 0.5.11(which is only available in the discords github thread :/). But there also seems to be another issue that is being caused. I'm not 100% on what's conflicting (was reading it in mobile)

**Comment by JimSkywalker** [comment]
I'm having this issue as well.

**Comment by WeidosOddities** [comment]
Fixed as of version 0.5.14
