### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SeveringHams** [WeidosOddities/Extended-Bogeys-Borked#8]
Can you add internal piston or no piston bogey variants of the most common bogeys? Like 0-4-0 and 0-6-0 with just the bogey frame, wheels and coupling rods? It would really help make tank engines look smaller, and on railroads with tight turns, the steam pistons wouldn't clip through the leading wheels.

I really like this mod, because it's actually maintained, and you're adding new stuff to it. Here's some trains I made:
![2024-07-14_19 39 44](https://github.com/user-attachments/assets/d934cb07-f449-43d9-8df0-e97320551d6e)
![2024-07-14_19 39 39](https://github.com/user-attachments/assets/adf20cfa-f7dc-453a-997c-c215b67023d6)
![2024-07-14_19 21 27](https://github.com/user-attachments/assets/d1c3833b-aef6-4e32-b7af-9c5284d04cb0)
![2024-07-14_19 21 18](https://github.com/user-attachments/assets/60205b7e-8b44-4517-b15b-ace801e6561d)

**Comment by WeidosOddities** [comment]
Done as of version 0.5.14
